### ISSUE TITLE
Exception if test results contain special XML character

### ISSUE THREAD

**Issue by balazs-zsoldos** [everit-org/eosgi-e4-plugin#10]
org.eclipse.core.runtime.CoreException: The test run could not be imported from file '/tmp/eosgi-testresult-1257863806840339667.xml'.
	at org.eclipse.jdt.internal.junit.model.JUnitModel.throwImportError(JUnitModel.java:555)
	at org.eclipse.jdt.internal.junit.model.JUnitModel.importTestRunSession(JUnitModel.java:396)
	at org.eclipse.jdt.junit.JUnitCore.importTestRunSession(JUnitCore.java:191)
	at org.everit.osgi.dev.e4.plugin.testresult.TestResultTracker.importTestFilesOfTrackedJVMIntoEclipseJUnitView(TestResultTracker.java:260)
	at org.everit.osgi.dev.e4.plugin.testresult.TestResultTracker.checkTestResultFolder(TestResultTracker.java:185)
	at org.everit.osgi.dev.e4.plugin.testresult.TestResultTracker.watchTestResultFolders(TestResultTracker.java:347)
	at java.lang.Thread.run(Thread.java:745)
    Caused by: org.xml.sax.SAXParseException; systemId: file:/tmp/eosgi-testresult-1257863806840339667.xml; lineNumber: 5; columnNumber: 52; The content of elements must consist of well-formed character data or markup.
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.createSAXParseException(ErrorHandlerWrapper.java:203)
	at com.sun.org.apache.xerces.internal.util.ErrorHandlerWrapper.fatalError(ErrorHandlerWrapper.java:177)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:400)
	at com.sun.org.apache.xerces.internal.impl.XMLErrorReporter.reportError(XMLErrorReporter.java:327)
	at com.sun.org.apache.xerces.internal.impl.XMLScanner.reportFatalError(XMLScanner.java:1465)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.startOfMarkup(XMLDocumentFragmentScannerImpl.java:2631)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2729)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:643)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:327)
	at javax.xml.parsers.SAXParser.parse(SAXParser.java:328)
	at org.eclipse.jdt.internal.junit.model.JUnitModel.importTestRunSession(JUnitModel.java:389)
	... 5 more

**Comment by balazs-zsoldos** [comment]
Fixed in 4.1.2
