### ISSUE TITLE
Error if there is no target folder for packaging type

### ISSUE THREAD

**Issue by balazs-zsoldos** [everit-org/eosgi-e4-plugin#7]
If the packaging type of a dependency on the workspace has pom packaging, there is no target folder normally during calling mvn:package. The following exception occures:

    java.io.UncheckedIOException: Cannot create description file after calling package: C:\Users\ext-zsoldosb\git\xxxx\yyy\target\.eosgi-e4-packaging-result.properties
        at org.everit.osgi.dev.e4.plugin.m2e.packaging.ProjectPackager.saveOrReplaceAttachedFilesDescription(ProjectPackager.java:356)
        at org.everit.osgi.dev.e4.plugin.m2e.packaging.ProjectPackager.lambda$3(ProjectPackager.java:308)
        at org.everit.osgi.dev.e4.plugin.m2e.M2EUtil.lambda$0(M2EUtil.java:96)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.executeBare(MavenExecutionContext.java:176)
        at org.eclipse.m2e.core.internal.embedder.MavenExecutionContext.execute(MavenExecutionContext.java:151)
        at org.everit.osgi.dev.e4.plugin.m2e.M2EUtil.executeInContext(M2EUtil.java:84)
        at org.everit.osgi.dev.e4.plugin.m2e.packaging.ProjectPackager.packageProject(ProjectPackager.java:287)
        at org.everit.osgi.dev.e4.plugin.EOSGiProject.packDependencies(EOSGiProject.java:419)
        at org.everit.osgi.dev.e4.plugin.EOSGiProject.atomicDist(EOSGiProject.java:190)
        at org.everit.osgi.dev.e4.plugin.EOSGiProject.atomicLaunch(EOSGiProject.java:266)
        at org.everit.osgi.dev.e4.plugin.EOSGiProject.lambda$7(EOSGiProject.java:397)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2240)
        at org.eclipse.core.internal.resources.Workspace.run(Workspace.java:2262)
        at org.everit.osgi.dev.e4.plugin.EOSGiProject.launch(EOSGiProject.java:395)
        at org.everit.osgi.dev.e4.plugin.ui.command.StartCommandHandler.lambda$0(StartCommandHandler.java:36)
        at org.eclipse.core.runtime.jobs.Job$2.run(Job.java:186)
        at org.eclipse.core.internal.jobs.Worker.run(Worker.java:55)
    Caused by: java.io.FileNotFoundException: C:\Users\ext-zsoldosb\git\xxx\yyy\target\.eosgi-e4-packaging-result.properties (A rendszer nem találja a megadott elérési utat)
        at java.io.FileOutputStream.open0(Native Method)
        at java.io.FileOutputStream.open(FileOutputStream.java:270)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
        at java.io.FileOutputStream.<init>(FileOutputStream.java:162)
        at org.everit.osgi.dev.e4.plugin.m2e.packaging.ProjectPackager.saveOrReplaceAttachedFilesDescription(ProjectPackager.java:353)
        ... 16 more

**Comment by balazs-zsoldos** [comment]
Fixed in 4.1.1
